version: '3.7'

services:

  app:
    build:
      context: .
      dockerfile: gradle.dockerfile
    volumes:
      - type: volume
        source: gradle-cache
        target: /home/gradle/.gradle
      - type: bind
        source: "${APP_PROJECT}"
        target: /application
    environment:
      - DB_CONTAINER_NAME=db
    ports:
      - 8080:8080
    user: "${HOST_UID}:${HOST_GID}"
    command: ["sh", "-c", "/bin/bash /application/run-script.sh"]
    networks:
      app-network:

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgreUser
      - POSTGRES_PASSWORD=postgreAdminDev
      - POSTGRES_DB=postgredb
    networks:
      app-network:

volumes:
  gradle-cache:

networks:
  app-network:
